version: '3.8'

services:
  app:
    image: alvaro2042/pruebaDevco:latest
    ports:
      - "8000:8000"
    depends_on:
      - MariaDB_prueba
    environment:
      - DB_HOST=MariaDB_prueba
      - DB_PORT=3306
      - DB_USER=alvaro2042
      - DB_PASSWORD=Alvaro@2042**
      - DB_NAME=bdpruebadevco

  bd:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Alvaro@2042**  
      - MYSQL_DATABASE=bdpruebadevco
    ports:
      - "3306:3306" 
      
